### ISSUE TITLE
Declare queue "default" for dispatch

### ISSUE THREAD

**Issue by Colomix** [spiral/roadrunner-jobs#30]
Hello! I fill config for dispatching to RabbitMQ's exchange, but at startup always create queue with name "default". These messages are intended for other microservices, whoever wants, subscribes to the exchange. How to stop the queue from being created?
```
amqp:
  addr: amqp://guest:guest@rabbitmq:5672/

jobs:
  pool:
    num_workers: 1
    max_jobs: 0
    allocate_timeout: 600s
    destroy_timeout: 600s

  pipelines:
    aggregator-event:
      config:
        driver: amqp
        exchange: amqp.topic
        exchange_type: topic
        routing_key: aggregator-event.user.action
        durable: true
```
