### ISSUE TITLE
[FEATURE REQUEST] Add ability to declare AMQP pipeline without queue name

### ISSUE THREAD

**Issue by iborysenko** [spiral/roadrunner-jobs#31]
Functionality already added https://github.com/spiral/roadrunner-jobs/issues/30

**Comment by iborysenko** [comment]
Hi, @butschster 
Could you please add this feature to client

**Comment by butschster** [comment]
Hi @iborysenko!

As I understand, you need to get stat for queue pipelines. I read it in the previous issue #30
I asked @rustatian  about empty queue name  and he told it won't work for getting stat. 

Could you provide more information about your case of usage empty queue name?

**Comment by iborysenko** [comment]
Hi @butschster 
I'm trying to build cross-service communication, and use RR instead of classic php-amqp driver for pushing and consuming. 

1. I would like to dispatch tasks with **only** specified `exchange` and `routing-key` and then produce them in another service
```yaml
jobs:
  consume: []
  pipelines:
    product_created_event: # this pipeline using only for producing tasks to broker 
      driver: amqp
      config:
        exchange: default
        routing_key: product-service.event.created
        exchange_type: direct
```
Latest release allowed me to do that, now I can dispatch task like 
```php
   $queue = $this->jobs->connect('product_created_event');
   $queue->dispatch(new PrepatedTask('product_created_event', ['foo' => 'bar']));
```
But I can't declare pipeline on the fly using
```php
   $queue = $this->jobs->create(new AMQPCreateInfo(.......))
   $queue->dispatch(new PrepatedTask('product_created_event', ['foo' => 'bar']));
```
because `AMQPCreateInfo` always require `queue` parameter, so make sense to do it optional

2. About stat object
As I mentioned above my project can contain both `produce-only` pipelines for producing tasks and `consume-only`

```yaml
jobs:
  consume: 
    - 'order_created_processing' 
  pipelines:
    product_created_event: # this pipeline using only for producing tasks to broker 
      driver: amqp
      config:
        exchange: default
        routing_key: product-service.event.created
        exchange_type: direct
    order_created_processing: # this pipeline using only for consuming incoming tasks
      driver: amqp
      config:
        exchange: default
        routing_key: order-service.event.created
        exchange_type: direct
        queue: product-service.consuming.order-service.event.created
```

If I run this config, and try to execute command like [ListPipelines](https://github.com/spiral/roadrunner-bridge/blob/2.0/src/Console/Command/Queue/ListCommand.php)
RR with throw 404 Queue Not found exception for pipeline `product_created_event` 
because now RR initialise queues only when you start pipeline
but I will never need this pipeline for running, make sense to return from RR side Stat-object with status `not-initialized` to prevent unexpected behaviour


Hope, it will be help 
P.S. I'm trying to integrate roadrunner/jobs to existed symfony application
