### ISSUE TITLE
Incorrect `.rr.yaml` sample configuration

### ISSUE THREAD

**Issue by rustatian** [spiral/roadrunner-jobs#33]
Hey @butschster 👋🏻 

```yaml
#
# RPC is required for tasks dispatching (client)
#
rpc:
    listen: tcp://127.0.0.1:6001

#
# This section configures the task consumer (server)
#
server:
    command: php consumer.php
    relay: pipes

#
# In this section, the jobs themselves are configured
#
jobs:
    consume: [ "test" ]   # List of RoadRunner queues that can be processed by 
                          # the consumer specified in the "server" section.
    pipelines:
        test:               # RoadRunner queue identifier
            driver: memory  # - Queue driver name
            queue: test       # - Internal (driver's) queue identifier <------- NO SUCH OPTION
```

There is no such key called `queue`, here is the correct reference: [link](https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1237)
